#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-sys
Version  : 3.4.3
Release  : 45
URL      : https://cran.r-project.org/src/contrib/sys_3.4.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sys_3.4.3.tar.gz
Summary  : Powerful and Reliable Tools for Running System Commands in R
Group    : Development/Tools
License  : MIT
Requires: R-sys-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
and consistent behavior across platforms. Supports clean interruption, timeout, 
    background tasks, and streaming STDIN / STDOUT / STDERR over binary or text 
    connections. Arguments on Windows automatically get encoded and quoted to work 
    on different locales.

%package lib
Summary: lib components for the R-sys package.
Group: Libraries

%description lib
lib components for the R-sys package.


%prep
%setup -q -n sys
pushd ..
cp -a sys buildavx2
popd
pushd ..
cp -a sys buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728052148

%install
export SOURCE_DATE_EPOCH=1728052148
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sys/DESCRIPTION
/usr/lib64/R/library/sys/INDEX
/usr/lib64/R/library/sys/LICENSE
/usr/lib64/R/library/sys/Meta/Rd.rds
/usr/lib64/R/library/sys/Meta/features.rds
/usr/lib64/R/library/sys/Meta/hsearch.rds
/usr/lib64/R/library/sys/Meta/links.rds
/usr/lib64/R/library/sys/Meta/nsInfo.rds
/usr/lib64/R/library/sys/Meta/package.rds
/usr/lib64/R/library/sys/NAMESPACE
/usr/lib64/R/library/sys/NEWS
/usr/lib64/R/library/sys/R/sys
/usr/lib64/R/library/sys/R/sys.rdb
/usr/lib64/R/library/sys/R/sys.rdx
/usr/lib64/R/library/sys/WORDLIST
/usr/lib64/R/library/sys/help/AnIndex
/usr/lib64/R/library/sys/help/aliases.rds
/usr/lib64/R/library/sys/help/paths.rds
/usr/lib64/R/library/sys/help/sys.rdb
/usr/lib64/R/library/sys/help/sys.rdx
/usr/lib64/R/library/sys/html/00Index.html
/usr/lib64/R/library/sys/html/R.css
/usr/lib64/R/library/sys/tests/spelling.R
/usr/lib64/R/library/sys/tests/testthat.R
/usr/lib64/R/library/sys/tests/testthat/test-binary.R
/usr/lib64/R/library/sys/tests/testthat/test-encoding.R
/usr/lib64/R/library/sys/tests/testthat/test-error.R
/usr/lib64/R/library/sys/tests/testthat/test-nesting.R
/usr/lib64/R/library/sys/tests/testthat/test-quote.R
/usr/lib64/R/library/sys/tests/testthat/test-stdin.R
/usr/lib64/R/library/sys/tests/testthat/test-stdout.R
/usr/lib64/R/library/sys/tests/testthat/test-timeout.R
/usr/lib64/R/library/sys/utf8.txt

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/sys/libs/sys.so
/V4/usr/lib64/R/library/sys/libs/sys.so
/usr/lib64/R/library/sys/libs/sys.so
